language: python
sudo: false
cache:
  apt: true
  directories:
    - $HOME/.cache/pip

python:
  - "2.7"

addons:
  apt:
# only add the two lines below if you need wkhtmltopdf for your tests
#    sources:
#      - pov-wkhtmltopdf
#    Search your sources alias here:
#      https://github.com/travis-ci/apt-source-whitelist/blob/master/ubuntu.json
    packages:
      - expect-dev  # provides unbuffer utility
      - python-lxml  # because pip installation is slow
      - python-simplejson
      - python-serial
      - python-yaml
      # FE
      - python-dev
      - swig
      - libffi-dev
      - libssl-dev
      - python-m2crypto
      - python-httplib2
#     Search your packages here:
#       https://github.com/travis-ci/apt-package-whitelist/blob/master/ubuntu-precise
#      - wkhtmltopdf  # only add if needed and check the before_install section below

# set up an X server to run wkhtmltopdf.
#before_install:
#  - "export DISPLAY=:99.0"
#  - "sh -e /etc/init.d/xvfb start"

env:
  global:
  - VERSION="9.0" TESTS="0" LINT_CHECK="0" TRANSIFEX="0"
  - TRANSIFEX_USER='jjscarafia'
  # This line contains the encrypted transifex password
  # To encrypt transifex password, install travis ruby utils with:
  #   $ gem install travis --user-install
  # and use:
    # $ travis encrypt TRANSIFEX_PASSWORD=your-password -r owner/project
  - secure: p8zaNOQOCuJzjvScomZQGYdiz+h7q+vrk08NnjgyuJ5HDf4zrRCYJFupAnfSj5XeNWd5/s9X4qvJNJVSSBR6/pqT91ZdomTM0/0/VI5tKoJHN1AlqDK2UqqWHh1ZJp5lY+Fm8vllBNrBiXuDVsjr4BNhm7gaVgrr8L0hvoAqRHwj2RbWlvMmY2kooIvxi86+4eHI/O2XJX6xL2s/dyk0b6CSLiVDEHU1qtBWoHzpxm2m6l19YIJK8yCB1Wp2uK6VvecrYGti9erQo4GlMQCVhqwB8togJ41ZmLf0I3V3OvTyjtWyjCOPSNGU1iHuky/wBOAdBYNQ8PQeJGt6OUJ8f7tg9TBgl+Oq0pmwPHDB+jVEcvHzm3uk/0vazbxkmnCZarASkUSgEshr/svdpOkO6u+J64nOfYVN+nS8lFl8at/wi+aF0zCZl7RTySOhh8qUNKu/vzDiyXJo4Ot2G3+3wiLjNfyBvtvkd+ks31UQ8pNn5/BUUiPobxTcpyLxMW8coW8QIUwrPYCOXZ30zKe1x9WZyJGW1slA4i9maHDD/I12DnqhrFdkj76/C+nKWI/DlQEt3Qb1306TqFz3LHGM8JFpaSwGpFOGhH7sQm170UOUE0J9in9gwkc+9XCCocxAE/DHaz4o+sd60I9heGDQ+LmCgANZHBx+j7U/YeA+njc=
  # Use the following lines if you need to manually change the transifex project slug or/and the transifex organization.
  # The default project slug is owner-repo_name-version (with dash in the version string).
  # The default organization is the owner of the repo.
  # The default fill up resources (TM) is True.
  # The default team is 23907. https://www.transifex.com/organization/oca/team/23907/
  # - TRANSIFEX_PROJECT_SLUG=
  - TRANSIFEX_ORGANIZATION='odoo-argentina'
  # - TRANSIFEX_FILL_UP_RESOURCES=
  - TRANSIFEX_TEAM='58916'

  matrix:
  - LINT_CHECK="1"
  - TRANSIFEX="1"
  - TESTS="1" ODOO_REPO="odoo/odoo"
# either use the two lines above or the two below. Don't change the default if
# it's not necessary (it is only necessary if modules in your repository can't
# be installed in the same database. And you get a huge speed penalty in your
# tests)
#  - TESTS="1.0" ODOO_REPO="odoo/odoo" UNIT_TEST="1"

virtualenv:
  system_site_packages: true

install:
  - git clone --depth=1 https://github.com/OCA/maintainer-quality-tools.git ${HOME}/maintainer-quality-tools
  - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
  - travis_install_nightly

script:
  - travis_run_tests

after_success:
  - travis_after_tests_success
